# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ogulniega.Launcher
PackageVersion: "13"
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
Installers:
- Architecture: x64
  InstallerUrl: https://ogulniega.com/files/installers/Ogulniega%20Minecraft_0.0.13_x64-setup.exe
  InstallerSha256: 6C19FD5EF36B59A987A6E239D97812FC077E56152BC2FE844044C827B01655B0
ManifestType: installer
ManifestVersion: 1.12.0
